name: Deploy production
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_NAME_PROD }}
          audience: ${{ secrets.WORKLOAD_IDENTITY_AUDIENCE_PROD }}
      - name: Deploy to Google Cloud Run
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID_PROD }}
          GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          ENVIRONMENT: production
        run: sh cmd/deploy_GCR.sh
